Env:
    output_dir: '/home/joty/code/solar_flow/outputs/diffsolar'
    logger: 'wandb'
    resume_ckpt: null
    DiffSolar_init_ckpt: null
    wandb:
      project: "diffsolar" 
      name: null  
      entity: "joty" 
      tags: ["diffusion", "solar"]  
      notes: "DiffSolar experiment"  
      group: null  
      save_code: true  
      mode: "online" 
    

datamodule:
  _target_: data.datamodules.SIS_DataModule
  dataset:
    data_path: '/home/joty/code/solar_flow/data'
    input_len: 8
    pred_len: 8
    stride: 1
    use_possible_starts: True
    years: {
      train: [ 2017, 2018, 2019, 2020,],
      val: [ 2021 ],
      test: [ 2022 ]}
  batch_size: 8
  num_workers: 10
  pin_memory: True

DiffSolar:
    Diffusion:
        prediction_type: 'epsilon' #'epsilon' or 'sample'
        ddim_num_steps: 1000
        ddim_num_inference_steps: 50
        ddim_beta_schedule: 'linear'
Training:
    use_ema: True
    ema_inv_gamma: 1.0
    ema_power: 0.75
    ema_max_decay: 0.995
    learning_rate: 1e-4
    lr_scheduler: 'cosine_with_restarts'
    lr_warmup_steps: 500
    num_cycles: 2
    adam_betas: [0.95, 0.999]
    adam_weight_decay: 1e-6
    adam_epsilon: 1e-8
    epochs: 300
    save_images_epochs: 4
    save_model_epochs: 4
    checkpointing_steps: 1000 #number of steps to save a resuming checkpoint
    gradient_accumulation_steps: 1 #4 for 128 resolution, 4 GPU training
    mixed_precision: "fp16" #["no", "fp16", "bf16"],