Env:
    output_dir: '/home/joty/code/solar_flow/outputs/diffsolar'
    logger: 'wandb'
    resume_ckpt: null
    DiffSolar_init_ckpt: null
    wandb:
      project: "diffsolar" 
      name: null  
      entity: "joty" 
      tags: ["diffusion", "solar"]  
      notes: "DiffSolar experiment"  
      group: null  
      save_code: true  
      mode: "online" 
    

datamodule:
  _target_: data.datamodules.SIS_DataModule
  dataset:
    data_path: '/home/joty/code/solar_flow/data'
    input_len: 8
    pred_len: 8
    stride: 1
    use_possible_starts: True
    years: {
      train: [ 2017, 2018, 2019, 2020,],
      val: [ 2021 ],
      test: [ 2022 ]}
  batch_size: 8
  num_workers: 10
  pin_memory: True

